---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-crds
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/crds
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-crds
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-network
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/network/overlays/prod
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_ENV: "prod"
      CLUSTER_NAME: "talos"
      CLUSTER_ZONE: "proxmox-01"
      BGP_PEER_ADDRESS: "192.168.30.1"
      LB_POOL_START: "192.168.31.10"
      LB_POOL_STOP: "192.168.31.250"
      GW_EXTERNAL_IP: "192.168.31.10"
      GW_INTERNAL_IP: "192.168.31.11"
