---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/region: "${CLUSTER_NAME}-${CLUSTER_ENV}"
      topology.kubernetes.io/zone: "${CLUSTER_ZONE}"
  bgpInstances:
    - name: "instance-${BGP_LOCAL_ASN}"
      # replaced by patch in overlay
      localASN: 0
      peers:
        - name: "peer-${BGP_LOCAL_ASN}-${CLUSTER_ZONE}-${CLUSTER_ENV}"
          # replaced by patch in overlay
          peerASN: 0
          peerAddress: "${BGP_PEER_ADDRESS}"
          peerConfigRef:
            name: "cilium-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  authSecretRef: bgp-auth-secret
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
