---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
# The secret needs to exist before the Helm releaes, otherwise the pods won't start and the health check will fail
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    apiToken: AgAByHszWq/5T61Zg2q9fT74Aralun7H9/UlQTSzx4/xiBfcDod+Gi5oDpmSHU28KOSWzuLHD+x+eNPzQN5RsiClmU8hw1QtcA3UUDOyMLrbCRIJaPI8OYd+frgSF6Kx5SHg93h3gZf7YWu3r2fkAAGY4DnkGm4SZZ3gfne1JeVL+ihT8m0uxvY5RtUUqAoZFxLPptSVPKu/pJ28ABRmxS6C+bOjR/vujLJlYuoNbmCyOASH58eElCHQcvqeGpiq2EXL4RsOPqra7QX+NgvxcsH+jIBKo1OmUwo3spSSBh8KxU6RBg+oAjxqEIYnIRt5Bn9V1UwZsdnamcCDrvkOSh/C56DYG72A2mcMHBETv4kAO93+anyArV4s7wQ7/JUu1P3N7Im1WNuj6vzZRiLgvrYz/6R24nS4sFEc8Vf+giVHAzXepEVAmddxszWmue0YW8E1nKY6kGms1AZZiKtJOy3YgUgGGE5AkU9D26XW3S+AO+SpvyLi8vGDEAGjDCMx8tizlA8pQZsPXUoLen1kYCYy9zqGwFygpmvlLjaNwgM6BhOhV+wBahFWlzGfg5EQpnn8PHyNUvMiu30O1tU9w0JmfOpZ4A8nel4RG5HzJ8ojCauXtbbqoUcrcnGuIdWqiUMr+8ffiq2so/1O1UHxoMknAugH67qVmrNLfnpsgpFDDhqbc11evRfwNIoXUNVJD5SkeJ6FJPdDF/TvLLz1nzORTGLiL+EnJgXn/k5dZzaXcemrMeHgGJTV
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: "1.16.1"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  values:
    provider:
      name: cloudflare
    sources:
      - gateway-httproute
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: apiToken
