---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 24h
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  targetNamespace: kyverno
  interval: 1h
  chart:
    spec:
      chart: kyverno
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 24h
  values:
    admissionController:
      replicas: 2
    backgroundController:
      replicas: 2
    cleanupController:
      replicas: 2
    reportsController:
      replicas: 2
