---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgCji9lUMHq+6u2iqKClTcPnQB8tRGgd0Zl3wF+3tmFc1JZtdlPm+Z4e93W5HPXuV/VVdGt02OGmB0LHrREc6FI5nbCRepVNXjVxy6RCr7IXWsvivYyErxUmiUHQnq86CbpTHNg5Qa8tzMuVlDFUH5c8v/KlbmMRGDjzYOGsra3OTxu82lUP466L6SQ8/58yTr44FnJghw3mM4biw352yvjt3IuwgoCElBakyKdWgUnJJZVrFbBwZYPWKrYwaq87bgIAn8P2olxhhHcwzXRJTnOi4wtV/RFa20n3qS9UYO2jABTng7g81pOND5w1QUEHPmpBH9Jxid1m2JXBpnxIzXkKL2pZsKFsySK9gu6I9YWYpZvPjRgFHIYcDzJywnufuMYvUJT/1Yas2V50NYXwz0iwUJJcm14PkyiOhp0NorbKXolYzmeG8qKI6MVDLrcAjM7Bcic7g1GbHs51JkYyEW4qsCJr2VZkTa6DSE+gXUoHmSlvQiwlFc4AU+Pg0JVDZFGlbWlHgIKS0U4iHhltMc009XbK8eZewiqetPjgOecKKkZy7TUxxyVChozOkX9Qw6WbzAGtbKRCLEOAFLnbBxSOlSBr4flC3HYjU2tzkv+NG3rYsLk35LXvyMVgKqqw7pvdZDpy7av0odXOsd/yrKfoGO/M09x+8JSdWvKApf3JNycGvb6GSvUJWCYOudwC+J1ynj8w0xiDSRffWnMA1JESU8Q2bvBUMNX2vYLmegxFZU53OXa3KSJtv/phnbjhbfO6ErZRh4oJr5xTrFc=
    username: AgBoHThC0PmCFZvyWyFgc9uSUJszxh0nuqe4IScNY++q2EqO4WEv5LpLiSmSzGjxbl6TYhEl8c4+JCSi2YnD7Yyytm+zf9/bI05vdmST7AKIuuS15JNV6kSQ79eAUafiBxgZNgYgkJoKKBKDy1wf4/tzeg6Cd5UMjV/B6ZvqUysJgUJ8YJX5nrXqe+HsWBUV7g3MRzkwY0jbWEIky+ID0fdaiy36TrSV7l1Iisig50lRPrlAZ82T2u1zPQm0N+OOlvh7J2R1M2rjrDsYgiIps5dfeCmsl8PRNqWmgl5ZNibr+GV6XOrq+DxpRF9iD5BNboAqD95Eo7IY4hppbnZbd6j2PvpcJbVq5D+qzp8p3uTiiZhVOAgifz8fNLiWJgq4hAQw3h3i/OfeAb/+/j7RqBU6BPHt+Rg/Pxyl1Q23LW2uuWoApHcTV/koQaBk1UwRU0SRoPrMopLMHHE/J2PGDgD9mJyJqhdUJdHcA/QV/07mOxJkBVrTyao8E1n+rif2VgNnaHnG5RYrSCzjLbXeASNCJsQruqRMvWppa4/SQcr5j6F0SDDMLrAaOkfZBMZjqKjMJqBUWR7d+iauMHAuPi+rqlckAMOcP/nrfHdRPk2iEVZrusE+0JaMsK1g9kj1kM5ASAyRfysF2qUF/MS4YopYFp9eQqSmWJfl48DUb/IjkWV+uOIEzn69QYL1lyaIE0FEpYSC8Q==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
    type: Opaque
