---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bgp-auth-secret
  namespace: kube-system
spec:
  encryptedData:
    password: AgANug1zbCZow3hA4C6gcRC73jvwO5t3c2IwrBA+/jaBuzrwogCn0pL5VHFvDCN2PUc6rk128aJcWxsnydniHeyclHJj3cV0phCKaKNjxoZ6ebmHBfh1A2piu8t3fGQ2UkbE95IcxPE9GJUU7Dh7dG3h3BWEPDUxdYy6Nx0ZAwHYFJqJHGb/b8PLdPG79dghZ6TJP+9giZt5VMEWKGQDwY02gVe5Wl92i4+PzUYsiOGeUh9A3KUsea/NJIw9aHtXFJxxMs/3BVBg7Q8rA+OBPUIEesOYadFt4K4sjjdZN2dySMywb3qVtchldecDlVnWluF3veDBfzFU9Vk345HivjbJGospK9UGH976lsPEq6nrHNM29WyPhpMuzM9mpRMJOhf1GgD2Swcyh3LlsyWY3hVWd+Nxoed5jrWH5udNBxTqZnC+ew38lIgXbIsAUuZlN1nE5Zsxa6V+OfqJCauao5d2Lzl1SCYBcL1hvU1Tq3zt7+KFCGlssccHXzTkQRCL6KLd3Mf37EROpGV01hztsRv3ffe62UdrSLVczjkXvyMALqZWHDL7ss4EA+u3wvVjVBIYexq2s8J4QFWnexUVx6Bqo1zpTh3x0VSoJKuGJDFPgWpgjVNblYjg9ggDr8UrSbJlXr17kMR+b1wd7vcORqio27FHFI2lg3D1T6HJGdDBfJRciePvVoVCCSH9C8F4S+gWG2tEzgS62WIlH2KxTq+4
  template:
    metadata:
      creationTimestamp: null
      name: bgp-auth-secret
      namespace: kube-system
    type: string
